export declare function test_ent_constructor(): boolean;
export declare function test_ent_getGeom(): boolean;
export declare function test_ent_getID(): boolean;
export declare function test_ent_getModel(): boolean;
export declare function test_ent_getAttribs(): boolean;
export declare function test_ent_getAttribValue(): boolean;
export declare function test_ent_setAttribValue(): boolean;
export declare function test_ent_getGroups(): boolean;
export declare function test_ent_addToGroup(): boolean;
